language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - name: Codecov
    uses: codecov/codecov-action@v2.1.0
    env:
      global:
        - CODECOV_TOKEN=:6c6d0984-8eb3-434b-a556-e187648347f2

